// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4TERM3qnxowTozA6OiPdc9bxPTzQ9BuI',
    appId: '1:6718566861:web:5cf47d39795b2344285484',
    messagingSenderId: '6718566861',
    projectId: 'mobdevfinals-691d0',
    authDomain: 'mobdevfinals-691d0.firebaseapp.com',
    storageBucket: 'mobdevfinals-691d0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS9rH-Ob90dP2-rveYZqWvG1mZmPD16_I',
    appId: '1:6718566861:android:7c48bedb9b8a6fbd285484',
    messagingSenderId: '6718566861',
    projectId: 'mobdevfinals-691d0',
    storageBucket: 'mobdevfinals-691d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRxxbu8r1y-KjhyTKrZQZ0bS4ger3x9IE',
    appId: '1:6718566861:ios:1e6a2ce6ff48c4ea285484',
    messagingSenderId: '6718566861',
    projectId: 'mobdevfinals-691d0',
    storageBucket: 'mobdevfinals-691d0.appspot.com',
    iosBundleId: 'com.example.inomProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRxxbu8r1y-KjhyTKrZQZ0bS4ger3x9IE',
    appId: '1:6718566861:ios:8f51e7419f190139285484',
    messagingSenderId: '6718566861',
    projectId: 'mobdevfinals-691d0',
    storageBucket: 'mobdevfinals-691d0.appspot.com',
    iosBundleId: 'com.example.inomProject.RunnerTests',
  );
}
